### ISSUE TITLE
demo怎么会是这个样子~是我运行的不对么？

### ISSUE THREAD

**Issue by fendoude007** [rongcloud/rongcloud-web-im-widget-h5#2]
![a6ee144d-a430-459e-a121-bc58b836b9b8](https://cloud.githubusercontent.com/assets/6134852/24789850/375b2858-1ba7-11e7-9f82-d030eb4a950e.png)
![a9b1fdaf-a1c1-489f-9299-b6f97fa2ade4](https://cloud.githubusercontent.com/assets/6134852/24789851/3790ece0-1ba7-11e7-846d-1211f248ecd4.png)

**Comment by shuise** [comment]
http://web.hitalk.im/widget/web/user1/index.html 给你一个可运行demo对照一下。需要确认依赖都ok，并且有正确可用的appkey和token

**Comment by hanwsscan** [comment]
运行不了....http://web.hitalk.im/widget/web/user1/index.html  请问还有没有可运行的....

**Comment by YongHao0** [comment]
可参考 SealTalk Web: http://web.sealtalk.im
